"""make rag chunks chapter only

Revision ID: 10c51e9a8843
Revises: 10d62ee37065
Create Date: 2026-06-10 02:57:57.257014

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '10c51e9a8843'
down_revision: Union[str, Sequence[str], None] = '10d62ee37065'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_document_chunks_topic_id'), table_name='document_chunks')
    op.drop_constraint(op.f('document_chunks_topic_id_fkey'), 'document_chunks', type_='foreignkey')
    op.drop_column('document_chunks', 'section_title')
    op.drop_column('document_chunks', 'topic_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document_chunks', sa.Column('topic_id', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('document_chunks', sa.Column('section_title', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('document_chunks_topic_id_fkey'), 'document_chunks', 'topics', ['topic_id'], ['id'], ondelete='SET NULL')
    op.create_index(op.f('ix_document_chunks_topic_id'), 'document_chunks', ['topic_id'], unique=False)
    # ### end Alembic commands ###
