"""make tutor chapter based with groups

Revision ID: 10d62ee37065
Revises: 010176bad173
Create Date: 2026-06-10 02:40:36.430605

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '10d62ee37065'
down_revision: Union[str, Sequence[str], None] = '010176bad173'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tutor_groups',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('subject_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tutor_groups_subject_id'), 'tutor_groups', ['subject_id'], unique=False)
    op.create_index(op.f('ix_tutor_groups_user_id'), 'tutor_groups', ['user_id'], unique=False)
    op.add_column('tutor_conversations', sa.Column('group_id', sa.UUID(), nullable=True))
    op.add_column('tutor_conversations', sa.Column('subject_id', sa.UUID(), nullable=False))
    op.add_column('tutor_conversations', sa.Column('chapter_id', sa.UUID(), nullable=False))
    op.add_column('tutor_conversations', sa.Column('rag_mode', sa.String(length=20), nullable=False))
    op.drop_index(op.f('ix_tutor_conversations_topic_id'), table_name='tutor_conversations')
    op.create_index(op.f('ix_tutor_conversations_chapter_id'), 'tutor_conversations', ['chapter_id'], unique=False)
    op.create_index(op.f('ix_tutor_conversations_group_id'), 'tutor_conversations', ['group_id'], unique=False)
    op.create_index(op.f('ix_tutor_conversations_subject_id'), 'tutor_conversations', ['subject_id'], unique=False)
    op.drop_constraint(op.f('tutor_conversations_topic_id_fkey'), 'tutor_conversations', type_='foreignkey')
    op.create_foreign_key(None, 'tutor_conversations', 'subjects', ['subject_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'tutor_conversations', 'chapters', ['chapter_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'tutor_conversations', 'tutor_groups', ['group_id'], ['id'], ondelete='CASCADE')
    op.drop_column('tutor_conversations', 'use_rag')
    op.drop_column('tutor_conversations', 'topic_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tutor_conversations', sa.Column('topic_id', sa.UUID(), autoincrement=False, nullable=False))
    op.add_column('tutor_conversations', sa.Column('use_rag', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'tutor_conversations', type_='foreignkey')
    op.drop_constraint(None, 'tutor_conversations', type_='foreignkey')
    op.drop_constraint(None, 'tutor_conversations', type_='foreignkey')
    op.create_foreign_key(op.f('tutor_conversations_topic_id_fkey'), 'tutor_conversations', 'topics', ['topic_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_tutor_conversations_subject_id'), table_name='tutor_conversations')
    op.drop_index(op.f('ix_tutor_conversations_group_id'), table_name='tutor_conversations')
    op.drop_index(op.f('ix_tutor_conversations_chapter_id'), table_name='tutor_conversations')
    op.create_index(op.f('ix_tutor_conversations_topic_id'), 'tutor_conversations', ['topic_id'], unique=False)
    op.drop_column('tutor_conversations', 'rag_mode')
    op.drop_column('tutor_conversations', 'chapter_id')
    op.drop_column('tutor_conversations', 'subject_id')
    op.drop_column('tutor_conversations', 'group_id')
    op.drop_index(op.f('ix_tutor_groups_user_id'), table_name='tutor_groups')
    op.drop_index(op.f('ix_tutor_groups_subject_id'), table_name='tutor_groups')
    op.drop_table('tutor_groups')
    # ### end Alembic commands ###
