"""make remediation chapter only

Revision ID: 1ee307dfb23c
Revises: 06738900ef8a
Create Date: 2026-06-10 03:53:10.564145

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1ee307dfb23c'
down_revision: Union[str, Sequence[str], None] = '06738900ef8a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('remediation_sessions', sa.Column('chapter_id', sa.UUID(), nullable=False))
    op.alter_column('remediation_sessions', 'weakness_label',
               existing_type=sa.VARCHAR(length=80),
               type_=sa.String(length=120),
               existing_nullable=False)
    op.drop_index(op.f('ix_remediation_sessions_topic_id'), table_name='remediation_sessions')
    op.create_index(op.f('ix_remediation_sessions_chapter_id'), 'remediation_sessions', ['chapter_id'], unique=False)
    op.drop_constraint(op.f('remediation_sessions_topic_id_fkey'), 'remediation_sessions', type_='foreignkey')
    op.create_foreign_key(None, 'remediation_sessions', 'chapters', ['chapter_id'], ['id'], ondelete='CASCADE')
    op.drop_column('remediation_sessions', 'topic_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('remediation_sessions', sa.Column('topic_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'remediation_sessions', type_='foreignkey')
    op.create_foreign_key(op.f('remediation_sessions_topic_id_fkey'), 'remediation_sessions', 'topics', ['topic_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_remediation_sessions_chapter_id'), table_name='remediation_sessions')
    op.create_index(op.f('ix_remediation_sessions_topic_id'), 'remediation_sessions', ['topic_id'], unique=False)
    op.alter_column('remediation_sessions', 'weakness_label',
               existing_type=sa.String(length=120),
               type_=sa.VARCHAR(length=80),
               existing_nullable=False)
    op.drop_column('remediation_sessions', 'chapter_id')
    # ### end Alembic commands ###
