"""create tutor conversation tables

Revision ID: 205e54d26420
Revises: 3398189efae5
Create Date: 2026-05-29 23:15:51.519623

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '205e54d26420'
down_revision: Union[str, Sequence[str], None] = '3398189efae5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tutor_conversations', sa.Column('use_rag', sa.Boolean(), nullable=False))
    op.add_column('tutor_messages', sa.Column('is_in_scope', sa.Boolean(), nullable=False))
    op.add_column('tutor_messages', sa.Column('is_source_grounded', sa.Boolean(), nullable=False))
    op.add_column('tutor_messages', sa.Column('prompt_tokens', sa.Integer(), nullable=True))
    op.add_column('tutor_messages', sa.Column('completion_tokens', sa.Integer(), nullable=True))
    op.add_column('tutor_messages', sa.Column('finish_reason', sa.String(length=30), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tutor_messages', 'finish_reason')
    op.drop_column('tutor_messages', 'completion_tokens')
    op.drop_column('tutor_messages', 'prompt_tokens')
    op.drop_column('tutor_messages', 'is_source_grounded')
    op.drop_column('tutor_messages', 'is_in_scope')
    op.drop_column('tutor_conversations', 'use_rag')
    # ### end Alembic commands ###
