"""create catalog tables

Revision ID: 231d29f746be
Revises: 8e1b1231ebd0
Create Date: 2026-05-29 19:22:47.900435

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '231d29f746be'
down_revision: Union[str, Sequence[str], None] = '8e1b1231ebd0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_lessons_topic_id'), table_name='lessons')
    op.drop_table('lessons')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lessons',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('topic_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('language', sa.VARCHAR(length=5), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('story_content', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('explanation_content', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('key_concept', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('common_mistake', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('source_label', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('source_page', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('is_published', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], name=op.f('lessons_topic_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('lessons_pkey')),
    sa.UniqueConstraint('topic_id', 'language', name=op.f('uq_lesson_topic_language'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_lessons_topic_id'), 'lessons', ['topic_id'], unique=False)
    # ### end Alembic commands ###
