"""create tutor conversation tables

Revision ID: 3398189efae5
Revises: b836ae7ebf8f
Create Date: 2026-05-29 21:47:25.888215

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3398189efae5'
down_revision: Union[str, Sequence[str], None] = 'b836ae7ebf8f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tutor_conversations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('topic_id', sa.UUID(), nullable=False),
    sa.Column('language', sa.String(length=5), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('provider', sa.String(length=30), nullable=False),
    sa.Column('model_name', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("language IN ('en', 'bn')", name='ck_tutor_conversation_language'),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tutor_conversations_topic_id'), 'tutor_conversations', ['topic_id'], unique=False)
    op.create_index(op.f('ix_tutor_conversations_user_id'), 'tutor_conversations', ['user_id'], unique=False)
    op.create_table('tutor_messages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('conversation_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('message_type', sa.String(length=20), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("message_type IN ('story', 'chat')", name='ck_tutor_message_type'),
    sa.CheckConstraint("role IN ('user', 'assistant')", name='ck_tutor_message_role'),
    sa.ForeignKeyConstraint(['conversation_id'], ['tutor_conversations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tutor_messages_conversation_id'), 'tutor_messages', ['conversation_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tutor_messages_conversation_id'), table_name='tutor_messages')
    op.drop_table('tutor_messages')
    op.drop_index(op.f('ix_tutor_conversations_user_id'), table_name='tutor_conversations')
    op.drop_index(op.f('ix_tutor_conversations_topic_id'), table_name='tutor_conversations')
    op.drop_table('tutor_conversations')
    # ### end Alembic commands ###
