"""add study tools module

Revision ID: 534632e4ddb9
Revises: e1a2f8c14e7c
Create Date: 2026-06-10 20:30:13.116167

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '534632e4ddb9'
down_revision: Union[str, Sequence[str], None] = 'e1a2f8c14e7c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_notes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('grade_id', sa.UUID(), nullable=True),
    sa.Column('subject_id', sa.UUID(), nullable=True),
    sa.Column('chapter_id', sa.UUID(), nullable=True),
    sa.Column('source_type', sa.String(length=40), nullable=False),
    sa.Column('source_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('ai_help_mode', sa.String(length=40), nullable=False),
    sa.Column('language', sa.String(length=5), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("language IN ('en', 'bn')", name='ck_ai_note_language'),
    sa.CheckConstraint("source_type IN ('raw_text', 'pdf', 'note', 'chapter', 'custom_tutor_chat')", name='ck_ai_note_source_type'),
    sa.ForeignKeyConstraint(['chapter_id'], ['chapters.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['grade_id'], ['grade_levels.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_notes_chapter_id'), 'ai_notes', ['chapter_id'], unique=False)
    op.create_index(op.f('ix_ai_notes_grade_id'), 'ai_notes', ['grade_id'], unique=False)
    op.create_index(op.f('ix_ai_notes_source_id'), 'ai_notes', ['source_id'], unique=False)
    op.create_index(op.f('ix_ai_notes_subject_id'), 'ai_notes', ['subject_id'], unique=False)
    op.create_index(op.f('ix_ai_notes_user_id'), 'ai_notes', ['user_id'], unique=False)
    op.create_table('flashcard_decks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('grade_id', sa.UUID(), nullable=True),
    sa.Column('subject_id', sa.UUID(), nullable=True),
    sa.Column('chapter_id', sa.UUID(), nullable=True),
    sa.Column('source_type', sa.String(length=40), nullable=False),
    sa.Column('source_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('language', sa.String(length=5), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("language IN ('en', 'bn')", name='ck_flashcard_deck_language'),
    sa.CheckConstraint("source_type IN ('raw_text', 'pdf', 'note', 'chapter', 'custom_tutor_chat')", name='ck_flashcard_deck_source_type'),
    sa.ForeignKeyConstraint(['chapter_id'], ['chapters.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['grade_id'], ['grade_levels.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_flashcard_decks_chapter_id'), 'flashcard_decks', ['chapter_id'], unique=False)
    op.create_index(op.f('ix_flashcard_decks_grade_id'), 'flashcard_decks', ['grade_id'], unique=False)
    op.create_index(op.f('ix_flashcard_decks_source_id'), 'flashcard_decks', ['source_id'], unique=False)
    op.create_index(op.f('ix_flashcard_decks_subject_id'), 'flashcard_decks', ['subject_id'], unique=False)
    op.create_index(op.f('ix_flashcard_decks_user_id'), 'flashcard_decks', ['user_id'], unique=False)
    op.create_table('study_documents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('grade_id', sa.UUID(), nullable=True),
    sa.Column('subject_id', sa.UUID(), nullable=True),
    sa.Column('chapter_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('language', sa.String(length=5), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('storage_path', sa.String(length=500), nullable=False),
    sa.Column('file_hash', sa.String(length=64), nullable=False),
    sa.Column('file_size_bytes', sa.Integer(), nullable=False),
    sa.Column('page_count', sa.Integer(), nullable=False),
    sa.Column('extracted_text', sa.Text(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('processing_status', sa.String(length=30), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("language IN ('en', 'bn')", name='ck_study_document_language'),
    sa.CheckConstraint("processing_status IN ('processed', 'needs_ocr', 'failed')", name='ck_study_document_processing_status'),
    sa.ForeignKeyConstraint(['chapter_id'], ['chapters.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['grade_id'], ['grade_levels.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_study_documents_chapter_id'), 'study_documents', ['chapter_id'], unique=False)
    op.create_index(op.f('ix_study_documents_file_hash'), 'study_documents', ['file_hash'], unique=False)
    op.create_index(op.f('ix_study_documents_grade_id'), 'study_documents', ['grade_id'], unique=False)
    op.create_index(op.f('ix_study_documents_subject_id'), 'study_documents', ['subject_id'], unique=False)
    op.create_index(op.f('ix_study_documents_user_id'), 'study_documents', ['user_id'], unique=False)
    op.create_table('flashcards',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('deck_id', sa.UUID(), nullable=False),
    sa.Column('front', sa.Text(), nullable=False),
    sa.Column('back', sa.Text(), nullable=False),
    sa.Column('hint', sa.Text(), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['deck_id'], ['flashcard_decks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_flashcards_deck_id'), 'flashcards', ['deck_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_flashcards_deck_id'), table_name='flashcards')
    op.drop_table('flashcards')
    op.drop_index(op.f('ix_study_documents_user_id'), table_name='study_documents')
    op.drop_index(op.f('ix_study_documents_subject_id'), table_name='study_documents')
    op.drop_index(op.f('ix_study_documents_grade_id'), table_name='study_documents')
    op.drop_index(op.f('ix_study_documents_file_hash'), table_name='study_documents')
    op.drop_index(op.f('ix_study_documents_chapter_id'), table_name='study_documents')
    op.drop_table('study_documents')
    op.drop_index(op.f('ix_flashcard_decks_user_id'), table_name='flashcard_decks')
    op.drop_index(op.f('ix_flashcard_decks_subject_id'), table_name='flashcard_decks')
    op.drop_index(op.f('ix_flashcard_decks_source_id'), table_name='flashcard_decks')
    op.drop_index(op.f('ix_flashcard_decks_grade_id'), table_name='flashcard_decks')
    op.drop_index(op.f('ix_flashcard_decks_chapter_id'), table_name='flashcard_decks')
    op.drop_table('flashcard_decks')
    op.drop_index(op.f('ix_ai_notes_user_id'), table_name='ai_notes')
    op.drop_index(op.f('ix_ai_notes_subject_id'), table_name='ai_notes')
    op.drop_index(op.f('ix_ai_notes_source_id'), table_name='ai_notes')
    op.drop_index(op.f('ix_ai_notes_grade_id'), table_name='ai_notes')
    op.drop_index(op.f('ix_ai_notes_chapter_id'), table_name='ai_notes')
    op.drop_table('ai_notes')
    # ### end Alembic commands ###
