"""make simulations chapter only

Revision ID: 5f95c51662d5
Revises: 1ee307dfb23c
Create Date: 2026-06-10 03:58:07.147784

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5f95c51662d5'
down_revision: Union[str, Sequence[str], None] = '1ee307dfb23c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_simulations_topic_id'), table_name='simulations')
    op.drop_constraint(op.f('simulations_topic_id_fkey'), 'simulations', type_='foreignkey')
    op.drop_column('simulations', 'topic_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('simulations', sa.Column('topic_id', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('simulations_topic_id_fkey'), 'simulations', 'topics', ['topic_id'], ['id'], ondelete='SET NULL')
    op.create_index(op.f('ix_simulations_topic_id'), 'simulations', ['topic_id'], unique=False)
    # ### end Alembic commands ###
