"""create simulations table

Revision ID: 7a86c85409bb
Revises: 231d29f746be
Create Date: 2026-05-29 19:29:59.374801

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7a86c85409bb'
down_revision: Union[str, Sequence[str], None] = '231d29f746be'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('simulations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('chapter_id', sa.UUID(), nullable=False),
    sa.Column('topic_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=180), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('language', sa.String(length=5), nullable=False),
    sa.Column('simulation_url', sa.String(length=500), nullable=False),
    sa.Column('thumbnail_url', sa.String(length=500), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("language IN ('en', 'bn', 'both')", name='ck_simulation_language'),
    sa.ForeignKeyConstraint(['chapter_id'], ['chapters.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_simulations_chapter_id'), 'simulations', ['chapter_id'], unique=False)
    op.create_index(op.f('ix_simulations_slug'), 'simulations', ['slug'], unique=True)
    op.create_index(op.f('ix_simulations_topic_id'), 'simulations', ['topic_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_simulations_topic_id'), table_name='simulations')
    op.drop_index(op.f('ix_simulations_slug'), table_name='simulations')
    op.drop_index(op.f('ix_simulations_chapter_id'), table_name='simulations')
    op.drop_table('simulations')
    # ### end Alembic commands ###
