"""add study tools module

Revision ID: 7e997bf6ec8b
Revises: 0a24d6c5ae3f
Create Date: 2026-06-10 23:09:50.710578

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7e997bf6ec8b'
down_revision: Union[str, Sequence[str], None] = '0a24d6c5ae3f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
