"""make diagnostics chapter only

Revision ID: 8365bf3902ef
Revises: ee4caa26e4b2
Create Date: 2026-06-10 03:49:21.908913

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8365bf3902ef'
down_revision: Union[str, Sequence[str], None] = 'ee4caa26e4b2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_chapter_statuses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('chapter_id', sa.UUID(), nullable=False),
    sa.Column('completion_status', sa.String(length=30), nullable=False),
    sa.Column('latest_score', sa.Float(), nullable=True),
    sa.Column('best_score', sa.Float(), nullable=True),
    sa.Column('strength_labels', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('weakness_labels', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("completion_status IN ('not_started', 'needs_practice', 'completed')", name='ck_user_chapter_completion_status'),
    sa.ForeignKeyConstraint(['chapter_id'], ['chapters.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'chapter_id', name='uq_user_chapter_status')
    )
    op.create_index(op.f('ix_user_chapter_statuses_chapter_id'), 'user_chapter_statuses', ['chapter_id'], unique=False)
    op.create_index(op.f('ix_user_chapter_statuses_user_id'), 'user_chapter_statuses', ['user_id'], unique=False)
    op.drop_index(op.f('ix_user_topic_status_topic_id'), table_name='user_topic_status')
    op.drop_index(op.f('ix_user_topic_status_user_id'), table_name='user_topic_status')
    op.drop_table('user_topic_status')
    op.create_unique_constraint('uq_chapter_subject_chapter_no', 'chapters', ['subject_id', 'chapter_no'])
    op.alter_column('diagnostic_answers', 'detected_weakness',
               existing_type=sa.VARCHAR(length=80),
               type_=sa.String(length=120),
               existing_nullable=True)
    op.alter_column('diagnostic_answers', 'confidence',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=30),
               existing_nullable=True)
    op.alter_column('diagnostic_answers', 'evaluation_method',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=30),
               existing_nullable=False)
    op.drop_constraint(op.f('uq_diagnostic_answer_session_question'), 'diagnostic_answers', type_='unique')
    op.alter_column('diagnostic_questions', 'question_type',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=30),
               existing_nullable=False)
    op.alter_column('diagnostic_questions', 'skill_label',
               existing_type=sa.VARCHAR(length=80),
               type_=sa.String(length=120),
               existing_nullable=False)
    op.alter_column('diagnostic_questions', 'explanation',
               existing_type=sa.TEXT(),
               nullable=True)
    op.drop_constraint(op.f('uq_diagnostic_question_session_order'), 'diagnostic_questions', type_='unique')
    op.add_column('diagnostic_sessions', sa.Column('chapter_id', sa.UUID(), nullable=False))
    op.alter_column('diagnostic_sessions', 'status',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=30),
               existing_nullable=False)
    op.alter_column('diagnostic_sessions', 'outcome',
               existing_type=sa.VARCHAR(length=30),
               type_=sa.String(length=40),
               existing_nullable=True)
    op.drop_index(op.f('ix_diagnostic_sessions_topic_id'), table_name='diagnostic_sessions')
    op.create_index(op.f('ix_diagnostic_sessions_chapter_id'), 'diagnostic_sessions', ['chapter_id'], unique=False)
    op.drop_constraint(op.f('diagnostic_sessions_topic_id_fkey'), 'diagnostic_sessions', type_='foreignkey')
    op.create_foreign_key(None, 'diagnostic_sessions', 'chapters', ['chapter_id'], ['id'], ondelete='CASCADE')
    op.drop_column('diagnostic_sessions', 'topic_id')
    op.drop_index(op.f('ix_grade_levels_slug'), table_name='grade_levels')
    op.create_index(op.f('ix_grade_levels_slug'), 'grade_levels', ['slug'], unique=False)
    op.create_unique_constraint('uq_grade_level_slug', 'grade_levels', ['slug'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_grade_level_slug', 'grade_levels', type_='unique')
    op.drop_index(op.f('ix_grade_levels_slug'), table_name='grade_levels')
    op.create_index(op.f('ix_grade_levels_slug'), 'grade_levels', ['slug'], unique=True)
    op.add_column('diagnostic_sessions', sa.Column('topic_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'diagnostic_sessions', type_='foreignkey')
    op.create_foreign_key(op.f('diagnostic_sessions_topic_id_fkey'), 'diagnostic_sessions', 'topics', ['topic_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_diagnostic_sessions_chapter_id'), table_name='diagnostic_sessions')
    op.create_index(op.f('ix_diagnostic_sessions_topic_id'), 'diagnostic_sessions', ['topic_id'], unique=False)
    op.alter_column('diagnostic_sessions', 'outcome',
               existing_type=sa.String(length=40),
               type_=sa.VARCHAR(length=30),
               existing_nullable=True)
    op.alter_column('diagnostic_sessions', 'status',
               existing_type=sa.String(length=30),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
    op.drop_column('diagnostic_sessions', 'chapter_id')
    op.create_unique_constraint(op.f('uq_diagnostic_question_session_order'), 'diagnostic_questions', ['session_id', 'display_order'], postgresql_nulls_not_distinct=False)
    op.alter_column('diagnostic_questions', 'explanation',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('diagnostic_questions', 'skill_label',
               existing_type=sa.String(length=120),
               type_=sa.VARCHAR(length=80),
               existing_nullable=False)
    op.alter_column('diagnostic_questions', 'question_type',
               existing_type=sa.String(length=30),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
    op.create_unique_constraint(op.f('uq_diagnostic_answer_session_question'), 'diagnostic_answers', ['session_id', 'question_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('diagnostic_answers', 'evaluation_method',
               existing_type=sa.String(length=30),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
    op.alter_column('diagnostic_answers', 'confidence',
               existing_type=sa.String(length=30),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)
    op.alter_column('diagnostic_answers', 'detected_weakness',
               existing_type=sa.String(length=120),
               type_=sa.VARCHAR(length=80),
               existing_nullable=True)
    op.drop_constraint('uq_chapter_subject_chapter_no', 'chapters', type_='unique')
    op.create_table('user_topic_status',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('topic_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('completion_status', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.Column('latest_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('best_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('strength_labels', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('weakness_labels', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('completed_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.CheckConstraint("completion_status::text = ANY (ARRAY['not_started'::character varying, 'needs_practice'::character varying, 'completed'::character varying]::text[])", name=op.f('ck_user_topic_completion_status')),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], name=op.f('user_topic_status_topic_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('user_topic_status_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('user_topic_status_pkey')),
    sa.UniqueConstraint('user_id', 'topic_id', name=op.f('uq_user_topic_status'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_user_topic_status_user_id'), 'user_topic_status', ['user_id'], unique=False)
    op.create_index(op.f('ix_user_topic_status_topic_id'), 'user_topic_status', ['topic_id'], unique=False)
    op.drop_index(op.f('ix_user_chapter_statuses_user_id'), table_name='user_chapter_statuses')
    op.drop_index(op.f('ix_user_chapter_statuses_chapter_id'), table_name='user_chapter_statuses')
    op.drop_table('user_chapter_statuses')
    # ### end Alembic commands ###
