"""add inbox custom tutor module

Revision ID: 86de832088d4
Revises: 96d4d3631bac
Create Date: 2026-06-10 18:04:37.570864

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '86de832088d4'
down_revision: Union[str, Sequence[str], None] = '96d4d3631bac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inbox_threads',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('assigned_admin_id', sa.UUID(), nullable=True),
    sa.Column('subject_id', sa.UUID(), nullable=True),
    sa.Column('chapter_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('source', sa.String(length=30), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('priority', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("priority IN ('low', 'normal', 'high')", name='ck_inbox_thread_priority'),
    sa.CheckConstraint("source IN ('custom_tutor', 'help', 'feedback')", name='ck_inbox_thread_source'),
    sa.CheckConstraint("status IN ('open', 'answered', 'closed')", name='ck_inbox_thread_status'),
    sa.ForeignKeyConstraint(['assigned_admin_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['chapter_id'], ['chapters.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inbox_threads_assigned_admin_id'), 'inbox_threads', ['assigned_admin_id'], unique=False)
    op.create_index(op.f('ix_inbox_threads_chapter_id'), 'inbox_threads', ['chapter_id'], unique=False)
    op.create_index(op.f('ix_inbox_threads_student_id'), 'inbox_threads', ['student_id'], unique=False)
    op.create_index(op.f('ix_inbox_threads_subject_id'), 'inbox_threads', ['subject_id'], unique=False)
    op.create_table('inbox_messages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('thread_id', sa.UUID(), nullable=False),
    sa.Column('sender_id', sa.UUID(), nullable=False),
    sa.Column('sender_role', sa.String(length=20), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('is_internal', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("sender_role IN ('student', 'admin', 'system')", name='ck_inbox_message_sender_role'),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['thread_id'], ['inbox_threads.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inbox_messages_sender_id'), 'inbox_messages', ['sender_id'], unique=False)
    op.create_index(op.f('ix_inbox_messages_thread_id'), 'inbox_messages', ['thread_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_inbox_messages_thread_id'), table_name='inbox_messages')
    op.drop_index(op.f('ix_inbox_messages_sender_id'), table_name='inbox_messages')
    op.drop_table('inbox_messages')
    op.drop_index(op.f('ix_inbox_threads_subject_id'), table_name='inbox_threads')
    op.drop_index(op.f('ix_inbox_threads_student_id'), table_name='inbox_threads')
    op.drop_index(op.f('ix_inbox_threads_chapter_id'), table_name='inbox_threads')
    op.drop_index(op.f('ix_inbox_threads_assigned_admin_id'), table_name='inbox_threads')
    op.drop_table('inbox_threads')
    # ### end Alembic commands ###
