"""create lessons table

Revision ID: 8e1b1231ebd0
Revises: 99afc03f6591
Create Date: 2026-05-29 19:17:28.912814

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8e1b1231ebd0'
down_revision: Union[str, Sequence[str], None] = '99afc03f6591'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lessons',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('topic_id', sa.UUID(), nullable=False),
    sa.Column('language', sa.String(length=5), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('story_content', sa.Text(), nullable=False),
    sa.Column('explanation_content', sa.Text(), nullable=False),
    sa.Column('key_concept', sa.Text(), nullable=True),
    sa.Column('common_mistake', sa.Text(), nullable=True),
    sa.Column('source_label', sa.String(length=255), nullable=False),
    sa.Column('source_page', sa.Integer(), nullable=True),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('topic_id', 'language', name='uq_lesson_topic_language')
    )
    op.create_index(op.f('ix_lessons_topic_id'), 'lessons', ['topic_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_lessons_topic_id'), table_name='lessons')
    op.drop_table('lessons')
    # ### end Alembic commands ###
