"""create diagnostics tables

Revision ID: 9eef8fa28e1a
Revises: b5abc62a8a44
Create Date: 2026-05-30 03:10:45.852398

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9eef8fa28e1a'
down_revision: Union[str, Sequence[str], None] = 'b5abc62a8a44'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_topic_status',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('topic_id', sa.UUID(), nullable=False),
    sa.Column('completion_status', sa.String(length=30), nullable=False),
    sa.Column('latest_score', sa.Float(), nullable=True),
    sa.Column('best_score', sa.Float(), nullable=True),
    sa.Column('strength_labels', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('weakness_labels', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("completion_status IN ('not_started', 'needs_practice', 'completed')", name='ck_user_topic_completion_status'),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'topic_id', name='uq_user_topic_status')
    )
    op.create_index(op.f('ix_user_topic_status_topic_id'), 'user_topic_status', ['topic_id'], unique=False)
    op.create_index(op.f('ix_user_topic_status_user_id'), 'user_topic_status', ['user_id'], unique=False)
    op.create_table('diagnostic_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('topic_id', sa.UUID(), nullable=False),
    sa.Column('conversation_id', sa.UUID(), nullable=True),
    sa.Column('language', sa.String(length=5), nullable=False),
    sa.Column('assessment_type', sa.String(length=30), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('question_count', sa.Integer(), nullable=False),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('percentage', sa.Float(), nullable=True),
    sa.Column('outcome', sa.String(length=30), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("assessment_type IN ('understanding_check', 'diagnostic_quiz', 'recheck')", name='ck_diagnostic_session_assessment_type'),
    sa.CheckConstraint("language IN ('en', 'bn')", name='ck_diagnostic_session_language'),
    sa.CheckConstraint("outcome IS NULL OR outcome IN ('understood', 'needs_diagnostic', 'strong', 'needs_practice')", name='ck_diagnostic_session_outcome'),
    sa.CheckConstraint("status IN ('generated', 'evaluated')", name='ck_diagnostic_session_status'),
    sa.ForeignKeyConstraint(['conversation_id'], ['tutor_conversations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_diagnostic_sessions_conversation_id'), 'diagnostic_sessions', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_diagnostic_sessions_topic_id'), 'diagnostic_sessions', ['topic_id'], unique=False)
    op.create_index(op.f('ix_diagnostic_sessions_user_id'), 'diagnostic_sessions', ['user_id'], unique=False)
    op.create_table('diagnostic_questions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('question_type', sa.String(length=20), nullable=False),
    sa.Column('question_text', sa.Text(), nullable=False),
    sa.Column('options', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('correct_answer', sa.Text(), nullable=False),
    sa.Column('evaluation_rubric', sa.Text(), nullable=True),
    sa.Column('skill_label', sa.String(length=80), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('max_score', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("question_type IN ('mcq', 'short_answer')", name='ck_diagnostic_question_type'),
    sa.ForeignKeyConstraint(['session_id'], ['diagnostic_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id', 'display_order', name='uq_diagnostic_question_session_order')
    )
    op.create_index(op.f('ix_diagnostic_questions_session_id'), 'diagnostic_questions', ['session_id'], unique=False)
    op.create_table('diagnostic_answers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('question_id', sa.UUID(), nullable=False),
    sa.Column('student_answer', sa.Text(), nullable=False),
    sa.Column('is_correct', sa.Boolean(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('feedback', sa.Text(), nullable=False),
    sa.Column('detected_weakness', sa.String(length=80), nullable=True),
    sa.Column('confidence', sa.String(length=20), nullable=True),
    sa.Column('evaluation_method', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("confidence IS NULL OR confidence IN ('low', 'medium', 'high')", name='ck_diagnostic_answer_confidence'),
    sa.CheckConstraint("evaluation_method IN ('automatic', 'deepseek')", name='ck_diagnostic_answer_evaluation_method'),
    sa.ForeignKeyConstraint(['question_id'], ['diagnostic_questions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['diagnostic_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id', 'question_id', name='uq_diagnostic_answer_session_question')
    )
    op.create_index(op.f('ix_diagnostic_answers_question_id'), 'diagnostic_answers', ['question_id'], unique=False)
    op.create_index(op.f('ix_diagnostic_answers_session_id'), 'diagnostic_answers', ['session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_diagnostic_answers_session_id'), table_name='diagnostic_answers')
    op.drop_index(op.f('ix_diagnostic_answers_question_id'), table_name='diagnostic_answers')
    op.drop_table('diagnostic_answers')
    op.drop_index(op.f('ix_diagnostic_questions_session_id'), table_name='diagnostic_questions')
    op.drop_table('diagnostic_questions')
    op.drop_index(op.f('ix_diagnostic_sessions_user_id'), table_name='diagnostic_sessions')
    op.drop_index(op.f('ix_diagnostic_sessions_topic_id'), table_name='diagnostic_sessions')
    op.drop_index(op.f('ix_diagnostic_sessions_conversation_id'), table_name='diagnostic_sessions')
    op.drop_table('diagnostic_sessions')
    op.drop_index(op.f('ix_user_topic_status_user_id'), table_name='user_topic_status')
    op.drop_index(op.f('ix_user_topic_status_topic_id'), table_name='user_topic_status')
    op.drop_table('user_topic_status')
    # ### end Alembic commands ###
