"""create document chunks table

Revision ID: b5abc62a8a44
Revises: 205e54d26420
Create Date: 2026-05-30 01:12:39.246123

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b5abc62a8a44'
down_revision: Union[str, Sequence[str], None] = '205e54d26420'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('document_chunks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('chapter_id', sa.UUID(), nullable=False),
    sa.Column('topic_id', sa.UUID(), nullable=False),
    sa.Column('language', sa.String(length=5), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('page_start', sa.Integer(), nullable=False),
    sa.Column('page_end', sa.Integer(), nullable=False),
    sa.Column('word_count', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("language IN ('en', 'bn')", name='ck_document_chunk_language'),
    sa.ForeignKeyConstraint(['chapter_id'], ['chapters.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document_id', 'topic_id', 'chunk_index', name='uq_document_topic_chunk_index')
    )
    op.create_index(op.f('ix_document_chunks_chapter_id'), 'document_chunks', ['chapter_id'], unique=False)
    op.create_index(op.f('ix_document_chunks_document_id'), 'document_chunks', ['document_id'], unique=False)
    op.create_index(op.f('ix_document_chunks_topic_id'), 'document_chunks', ['topic_id'], unique=False)
    op.drop_constraint(op.f('uq_document_chapter_language_source'), 'documents', type_='unique')
    op.create_unique_constraint('uq_document_chapter_language_source_type', 'documents', ['chapter_id', 'language', 'source_type'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_document_chapter_language_source_type', 'documents', type_='unique')
    op.create_unique_constraint(op.f('uq_document_chapter_language_source'), 'documents', ['chapter_id', 'language', 'source_type'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_document_chunks_topic_id'), table_name='document_chunks')
    op.drop_index(op.f('ix_document_chunks_document_id'), table_name='document_chunks')
    op.drop_index(op.f('ix_document_chunks_chapter_id'), table_name='document_chunks')
    op.drop_table('document_chunks')
    # ### end Alembic commands ###
