"""make rag chunks chapter wise

Revision ID: c029a0ddcbbe
Revises: b658aab2f51f
Create Date: 2026-06-10 02:30:33.189212

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c029a0ddcbbe'
down_revision: Union[str, Sequence[str], None] = 'b658aab2f51f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document_chunks', sa.Column('section_title', sa.String(length=255), nullable=True))
    op.alter_column('document_chunks', 'topic_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_constraint(op.f('uq_document_topic_chunk_index'), 'document_chunks', type_='unique')
    op.create_unique_constraint('uq_document_chapter_chunk_index', 'document_chunks', ['document_id', 'chapter_id', 'chunk_index'])
    op.drop_constraint(op.f('document_chunks_topic_id_fkey'), 'document_chunks', type_='foreignkey')
    op.create_foreign_key(None, 'document_chunks', 'topics', ['topic_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'document_chunks', type_='foreignkey')
    op.create_foreign_key(op.f('document_chunks_topic_id_fkey'), 'document_chunks', 'topics', ['topic_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('uq_document_chapter_chunk_index', 'document_chunks', type_='unique')
    op.create_unique_constraint(op.f('uq_document_topic_chunk_index'), 'document_chunks', ['document_id', 'topic_id', 'chunk_index'], postgresql_nulls_not_distinct=False)
    op.alter_column('document_chunks', 'topic_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('document_chunks', 'section_title')
    # ### end Alembic commands ###
