"""add study tool artifacts

Revision ID: cad8dee59dfe
Revises: a9c4db9041b2
Create Date: 2026-06-10 21:03:10.761819

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cad8dee59dfe'
down_revision: Union[str, Sequence[str], None] = 'a9c4db9041b2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('study_artifacts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('grade_id', sa.UUID(), nullable=True),
    sa.Column('subject_id', sa.UUID(), nullable=True),
    sa.Column('chapter_id', sa.UUID(), nullable=True),
    sa.Column('source_type', sa.String(length=40), nullable=False),
    sa.Column('source_id', sa.UUID(), nullable=True),
    sa.Column('artifact_type', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('content_markdown', sa.Text(), nullable=False),
    sa.Column('content_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('language', sa.String(length=5), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("artifact_type IN ('mind_map', 'worksheet', 'formula_sheet', 'important_questions')", name='ck_study_artifact_type'),
    sa.CheckConstraint("language IN ('en', 'bn')", name='ck_study_artifact_language'),
    sa.CheckConstraint("source_type IN ('raw_text', 'pdf', 'note', 'chapter', 'custom_tutor_chat')", name='ck_study_artifact_source_type'),
    sa.ForeignKeyConstraint(['chapter_id'], ['chapters.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['grade_id'], ['grade_levels.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_study_artifacts_artifact_type'), 'study_artifacts', ['artifact_type'], unique=False)
    op.create_index(op.f('ix_study_artifacts_chapter_id'), 'study_artifacts', ['chapter_id'], unique=False)
    op.create_index(op.f('ix_study_artifacts_grade_id'), 'study_artifacts', ['grade_id'], unique=False)
    op.create_index(op.f('ix_study_artifacts_source_id'), 'study_artifacts', ['source_id'], unique=False)
    op.create_index(op.f('ix_study_artifacts_subject_id'), 'study_artifacts', ['subject_id'], unique=False)
    op.create_index(op.f('ix_study_artifacts_user_id'), 'study_artifacts', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_study_artifacts_user_id'), table_name='study_artifacts')
    op.drop_index(op.f('ix_study_artifacts_subject_id'), table_name='study_artifacts')
    op.drop_index(op.f('ix_study_artifacts_source_id'), table_name='study_artifacts')
    op.drop_index(op.f('ix_study_artifacts_grade_id'), table_name='study_artifacts')
    op.drop_index(op.f('ix_study_artifacts_chapter_id'), table_name='study_artifacts')
    op.drop_index(op.f('ix_study_artifacts_artifact_type'), table_name='study_artifacts')
    op.drop_table('study_artifacts')
    # ### end Alembic commands ###
