"""create remediation tables

Revision ID: de2f87717f56
Revises: 9eef8fa28e1a
Create Date: 2026-05-30 05:02:15.714238

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'de2f87717f56'
down_revision: Union[str, Sequence[str], None] = '9eef8fa28e1a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('remediation_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('topic_id', sa.UUID(), nullable=False),
    sa.Column('diagnostic_session_id', sa.UUID(), nullable=False),
    sa.Column('weakness_label', sa.String(length=80), nullable=False),
    sa.Column('language', sa.String(length=5), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('is_source_grounded', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("language IN ('en', 'bn')", name='ck_remediation_session_language'),
    sa.CheckConstraint("status IN ('generated', 'completed', 'needs_retry')", name='ck_remediation_session_status'),
    sa.ForeignKeyConstraint(['diagnostic_session_id'], ['diagnostic_sessions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_remediation_sessions_diagnostic_session_id'), 'remediation_sessions', ['diagnostic_session_id'], unique=False)
    op.create_index(op.f('ix_remediation_sessions_topic_id'), 'remediation_sessions', ['topic_id'], unique=False)
    op.create_index(op.f('ix_remediation_sessions_user_id'), 'remediation_sessions', ['user_id'], unique=False)
    op.create_table('remediation_contents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('remediation_session_id', sa.UUID(), nullable=False),
    sa.Column('weakness_statement', sa.Text(), nullable=False),
    sa.Column('micro_lesson', sa.Text(), nullable=False),
    sa.Column('guided_example', sa.Text(), nullable=False),
    sa.Column('partially_solved_problem', sa.Text(), nullable=False),
    sa.Column('recheck_question', sa.Text(), nullable=False),
    sa.Column('expected_answer', sa.Text(), nullable=False),
    sa.Column('next_action', sa.String(length=80), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['remediation_session_id'], ['remediation_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('remediation_session_id', name='uq_remediation_content_session')
    )
    op.create_index(op.f('ix_remediation_contents_remediation_session_id'), 'remediation_contents', ['remediation_session_id'], unique=False)
    op.create_table('remediation_rechecks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('remediation_session_id', sa.UUID(), nullable=False),
    sa.Column('student_answer', sa.Text(), nullable=False),
    sa.Column('is_correct', sa.Boolean(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('feedback', sa.Text(), nullable=False),
    sa.Column('next_action', sa.String(length=80), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['remediation_session_id'], ['remediation_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_remediation_rechecks_remediation_session_id'), 'remediation_rechecks', ['remediation_session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_remediation_rechecks_remediation_session_id'), table_name='remediation_rechecks')
    op.drop_table('remediation_rechecks')
    op.drop_index(op.f('ix_remediation_contents_remediation_session_id'), table_name='remediation_contents')
    op.drop_table('remediation_contents')
    op.drop_index(op.f('ix_remediation_sessions_user_id'), table_name='remediation_sessions')
    op.drop_index(op.f('ix_remediation_sessions_topic_id'), table_name='remediation_sessions')
    op.drop_index(op.f('ix_remediation_sessions_diagnostic_session_id'), table_name='remediation_sessions')
    op.drop_table('remediation_sessions')
    # ### end Alembic commands ###
