"""add custom tutor ai chat

Revision ID: e1a2f8c14e7c
Revises: 86de832088d4
Create Date: 2026-06-10 18:35:09.843669

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e1a2f8c14e7c'
down_revision: Union[str, Sequence[str], None] = '86de832088d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('custom_tutor_chats',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('grade_id', sa.UUID(), nullable=True),
    sa.Column('subject_id', sa.UUID(), nullable=True),
    sa.Column('chapter_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('language', sa.String(length=5), nullable=False),
    sa.Column('is_archived', sa.Boolean(), nullable=False),
    sa.Column('message_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("language IN ('en', 'bn')", name='ck_custom_tutor_chat_language'),
    sa.ForeignKeyConstraint(['chapter_id'], ['chapters.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['grade_id'], ['grade_levels.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_custom_tutor_chats_chapter_id'), 'custom_tutor_chats', ['chapter_id'], unique=False)
    op.create_index(op.f('ix_custom_tutor_chats_grade_id'), 'custom_tutor_chats', ['grade_id'], unique=False)
    op.create_index(op.f('ix_custom_tutor_chats_subject_id'), 'custom_tutor_chats', ['subject_id'], unique=False)
    op.create_index(op.f('ix_custom_tutor_chats_user_id'), 'custom_tutor_chats', ['user_id'], unique=False)
    op.create_table('custom_tutor_messages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('chat_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('prompt_tokens', sa.Integer(), nullable=True),
    sa.Column('completion_tokens', sa.Integer(), nullable=True),
    sa.Column('finish_reason', sa.String(length=80), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("role IN ('user', 'assistant')", name='ck_custom_tutor_message_role'),
    sa.ForeignKeyConstraint(['chat_id'], ['custom_tutor_chats.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_custom_tutor_messages_chat_id'), 'custom_tutor_messages', ['chat_id'], unique=False)
    op.drop_index(op.f('ix_inbox_messages_sender_id'), table_name='inbox_messages')
    op.drop_index(op.f('ix_inbox_messages_thread_id'), table_name='inbox_messages')
    op.drop_table('inbox_messages')
    op.drop_index(op.f('ix_inbox_threads_assigned_admin_id'), table_name='inbox_threads')
    op.drop_index(op.f('ix_inbox_threads_chapter_id'), table_name='inbox_threads')
    op.drop_index(op.f('ix_inbox_threads_student_id'), table_name='inbox_threads')
    op.drop_index(op.f('ix_inbox_threads_subject_id'), table_name='inbox_threads')
    op.drop_table('inbox_threads')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inbox_threads',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('student_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('assigned_admin_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('subject_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('chapter_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('title', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('source', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.Column('priority', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.CheckConstraint("priority::text = ANY (ARRAY['low'::character varying, 'normal'::character varying, 'high'::character varying]::text[])", name=op.f('ck_inbox_thread_priority')),
    sa.CheckConstraint("source::text = ANY (ARRAY['custom_tutor'::character varying, 'help'::character varying, 'feedback'::character varying]::text[])", name=op.f('ck_inbox_thread_source')),
    sa.CheckConstraint("status::text = ANY (ARRAY['open'::character varying, 'answered'::character varying, 'closed'::character varying]::text[])", name=op.f('ck_inbox_thread_status')),
    sa.ForeignKeyConstraint(['assigned_admin_id'], ['users.id'], name=op.f('inbox_threads_assigned_admin_id_fkey'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['chapter_id'], ['chapters.id'], name=op.f('inbox_threads_chapter_id_fkey'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], name=op.f('inbox_threads_student_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], name=op.f('inbox_threads_subject_id_fkey'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('inbox_threads_pkey'))
    )
    op.create_index(op.f('ix_inbox_threads_subject_id'), 'inbox_threads', ['subject_id'], unique=False)
    op.create_index(op.f('ix_inbox_threads_student_id'), 'inbox_threads', ['student_id'], unique=False)
    op.create_index(op.f('ix_inbox_threads_chapter_id'), 'inbox_threads', ['chapter_id'], unique=False)
    op.create_index(op.f('ix_inbox_threads_assigned_admin_id'), 'inbox_threads', ['assigned_admin_id'], unique=False)
    op.create_table('inbox_messages',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('thread_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('sender_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('sender_role', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('body', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('is_internal', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.CheckConstraint("sender_role::text = ANY (ARRAY['student'::character varying, 'admin'::character varying, 'system'::character varying]::text[])", name=op.f('ck_inbox_message_sender_role')),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], name=op.f('inbox_messages_sender_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['thread_id'], ['inbox_threads.id'], name=op.f('inbox_messages_thread_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('inbox_messages_pkey'))
    )
    op.create_index(op.f('ix_inbox_messages_thread_id'), 'inbox_messages', ['thread_id'], unique=False)
    op.create_index(op.f('ix_inbox_messages_sender_id'), 'inbox_messages', ['sender_id'], unique=False)
    op.drop_index(op.f('ix_custom_tutor_messages_chat_id'), table_name='custom_tutor_messages')
    op.drop_table('custom_tutor_messages')
    op.drop_index(op.f('ix_custom_tutor_chats_user_id'), table_name='custom_tutor_chats')
    op.drop_index(op.f('ix_custom_tutor_chats_subject_id'), table_name='custom_tutor_chats')
    op.drop_index(op.f('ix_custom_tutor_chats_grade_id'), table_name='custom_tutor_chats')
    op.drop_index(op.f('ix_custom_tutor_chats_chapter_id'), table_name='custom_tutor_chats')
    op.drop_table('custom_tutor_chats')
    # ### end Alembic commands ###
